import * as Tabs from '@radix-ui/react-tabs'
import {
  Activity,
  Archive,
  Bug,
  CheckCircle2,
  ClipboardList,
  Copy,
  Cpu,
  Download,
  FileText,
  FilePlus,
  FileJson,
  FileWarning,
  FolderOpen,
  FolderPlus,
  Hammer,
  PackageOpen,
  RadioTower,
  RotateCcw,
  Send,
  ShieldCheck,
  Terminal,
  Trash2,
  Volume2,
  Wrench,
} from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import ashfallCardImage from '../../assets/modpacks/ashfall-card.webp'
import { repairActions } from '../../data/bundledLauncherData'
import { crashAnalyzer } from '../../services/CrashAnalyzer'
import { diagnosticReportService } from '../../services/DiagnosticReportService'
import { discordPostGenerator } from '../../services/DiscordPostGenerator'
import { logAnalyzer } from '../../services/LogAnalyzer'
import { launchService } from '../../services/LaunchService'
import { repairService } from '../../services/RepairService'
import { worldScannerService } from '../../services/WorldScannerService'
import { invokeNative } from '../../services/nativeBridge'
import { useDiagnosticsStore } from '../../stores/diagnosticsStore'
import { useLauncherStore } from '../../stores/launcherStore'
import { usePackOsStore } from '../../stores/packOsStore'
import { useProfileStore } from '../../stores/profileStore'
import { useReadinessStore } from '../../stores/readinessStore'
import { useSettingsStore } from '../../stores/settingsStore'
import type { ModpackExportReport, NativeRepairResult, NativeRollbackRestoreResult, NativeVerifyResult } from '../../types/native'
import type { AssetValidationReport, LogEntry, WorldCompatibilityReport } from '../../types/diagnostics'
import type { MinecraftLauncherProfileStatus } from '../../types/launch'
import type { ToolsTabId } from '../../types/launcher'
import { packOsHealthStatus, packOsPrimaryReason, packOsSafeCommands, packOsUiStateLabel, selectedPackOsPack } from '../../utils/packosStatus'
import { CrashAnalyzerCard } from '../cyber/CrashAnalyzerCard'
import { CyberButton } from '../cyber/CyberButton'
import { GlassCard } from '../cyber/GlassCard'
import { LogViewer } from '../cyber/LogViewer'
import { MetricCard } from '../cyber/MetricCard'
import { ProgressBar } from '../cyber/ProgressBar'
import { SectionHeader } from '../cyber/SectionHeader'
import { StatusChip } from '../cyber/StatusChip'
import { ToggleRow } from '../cyber/ToggleRow'
import { EcosystemHealthPage } from '../ecosystem/EcosystemHealthPage'
import { LogsPage } from '../logs/LogsPage'

const healthIcons = [Cpu, Terminal, RadioTower, Volume2, Bug, ShieldCheck, Activity]
const fallbackExportVersion = 'catalog-package'
const defaultExportChangelog = [
  'Ashfall packaged from the selected local source folder.',
  'Strict SHA-256 manifest and verified zip artifact release.',
  'Minecraft Launcher handoff path prepared for beta testers.',
]
const defaultReleaseNotes = [
  'Ashfall export generated by ECHO Launcher.',
  'Install only through approved Catalog metadata.',
]

type ExportExtraInclude = {
  kind: 'folder' | 'file'
  path: string
}

function defaultExportFileName(version: string) {
  return `Ashfall-${version || fallbackExportVersion}.echo-pack.zip`
}

function ensureEchoPackFileName(value: string, version: string) {
  const fileName = value.trim().split(/[\\/]/u).filter(Boolean).pop() || defaultExportFileName(version)
  return fileName.endsWith('.echo-pack.zip') ? fileName : `${fileName}.echo-pack.zip`
}

function joinOutputPath(outputDir: string, fileName: string) {
  const cleanDir = outputDir.trim().replace(/[\\/]+$/u, '')
  const cleanFile = fileName.trim().replace(/^[\\/]+/u, '')
  if (!cleanDir) return cleanFile
  return `${cleanDir}${cleanDir.includes('\\') ? '\\' : '/'}${cleanFile}`
}

function textLines(value: string) {
  return value.split(/\r?\n/u).map((line) => line.trim()).filter(Boolean)
}

function pathLabel(sourcePath: string | undefined, targetPath: string) {
  if (!sourcePath) return targetPath
  const source = sourcePath.replace(/[\\/]+$/u, '').toLowerCase()
  const target = targetPath.toLowerCase()
  if (target === source) return '.'
  if (target.startsWith(`${source}\\`) || target.startsWith(`${source}/`)) {
    return targetPath.slice(sourcePath.replace(/[\\/]+$/u, '').length + 1)
  }
  return targetPath
}

export function ToolsPage() {
  const [repairReport, setRepairReport] = useState<NativeRepairResult | null>(null)
  const [rollbackReport, setRollbackReport] = useState<NativeRollbackRestoreResult | null>(null)
  const [verifyReport, setVerifyReport] = useState<NativeVerifyResult | null>(null)
  const [assetReport, setAssetReport] = useState<AssetValidationReport | null>(null)
  const [worldReport, setWorldReport] = useState<WorldCompatibilityReport | null>(null)
  const [minecraftLauncherStatus, setMinecraftLauncherStatus] = useState<MinecraftLauncherProfileStatus | null>(null)
  const [modpackExportReport, setModpackExportReport] = useState<ModpackExportReport | null>(null)
  const addToast = useLauncherStore((state) => state.addToast)
  const activeTab = useLauncherStore((state) => state.activeToolsTab)
  const setActiveTab = useLauncherStore((state) => state.setActiveToolsTab)
  const selectedProfileId = useLauncherStore((state) => state.selectedProfileId)
  const setSelectedVariant = useLauncherStore((state) => state.setSelectedVariant)
  const supportGuideUrl = useSettingsStore((state) => state.supportGuideUrl)
  const applyPerformancePreset = useSettingsStore((state) => state.applyPerformancePreset)
  const readiness = useReadinessStore((state) => state.readiness)
  const refreshReadiness = useReadinessStore((state) => state.refreshReadiness)
  const packOs = usePackOsStore((state) => state.packOs)
  const refreshPackOs = usePackOsStore((state) => state.refreshPackOs)
  const profiles = useProfileStore((state) => state.profiles)
  const selectedProfile = profiles.find((profile) => profile.id === selectedProfileId) ?? profiles[0]
  const initialExportVersion = selectedProfile?.version ?? fallbackExportVersion
  const [exportVersion, setExportVersion] = useState(initialExportVersion)
  const [exportOutputDir, setExportOutputDir] = useState('')
  const [exportFileName, setExportFileName] = useState(defaultExportFileName(initialExportVersion))
  const [exportChangelog, setExportChangelog] = useState(defaultExportChangelog.join('\n'))
  const [exportReleaseNotes, setExportReleaseNotes] = useState(defaultReleaseNotes.join('\n'))
  const [includeResourcepacks, setIncludeResourcepacks] = useState(true)
  const [includeShaderpacks, setIncludeShaderpacks] = useState(true)
  const [includeServerSafeFiles, setIncludeServerSafeFiles] = useState(true)
  const [emitReleaseSidecars, setEmitReleaseSidecars] = useState(true)
  const [extraIncludes, setExtraIncludes] = useState<ExportExtraInclude[]>([])
  const repairActive = useDiagnosticsStore((state) => state.repairActive)
  const repairProgress = useDiagnosticsStore((state) => state.repairProgress)
  const verifyActive = useDiagnosticsStore((state) => state.verifyActive)
  const verifyProgress = useDiagnosticsStore((state) => state.verifyProgress)
  const currentFile = useDiagnosticsStore((state) => state.currentFile)
  const scannedFiles = useDiagnosticsStore((state) => state.scannedFiles)
  const totalFiles = useDiagnosticsStore((state) => state.totalFiles)
  const startRepair = useDiagnosticsStore((state) => state.startRepair)
  const tickRepair = useDiagnosticsStore((state) => state.tickRepair)
  const finishRepair = useDiagnosticsStore((state) => state.finishRepair)
  const startVerification = useDiagnosticsStore((state) => state.startVerification)
  const tickVerification = useDiagnosticsStore((state) => state.tickVerification)
  const finishVerification = useDiagnosticsStore((state) => state.finishVerification)
  const errorsFound = useDiagnosticsStore((state) => state.errorsFound)
  const [logEntries, setLogEntries] = useState<LogEntry[]>([])
  const analysis = useMemo(
    () =>
      logEntries.length
        ? crashAnalyzer.classifyCrash(logEntries)
        : {
            title: 'No Log Data Yet',
            severity: 'Warning' as const,
            likelyCause: 'No Ashfall logs were found yet.',
            suggestedFix: 'Install or launch Ashfall, then open Logs.',
            signatures: [],
          },
    [logEntries],
  )
  const selectedReadiness = readiness?.profile?.id === selectedProfile.id ? readiness : null
  const readinessWarnings = selectedReadiness?.warnings.length ?? 0
  const selectedPackOs = selectedPackOsPack(packOs, selectedProfileId)
  const packOsCommands = packOsSafeCommands(packOs, selectedPackOs)
  const runtimeChecks = [
    {
      id: 'packos',
      name: 'PackOS',
      status: packOsHealthStatus(selectedPackOs),
      detail: selectedPackOs ? `${packOsUiStateLabel(selectedPackOs.uiState)}: ${packOsPrimaryReason(packOs, selectedProfileId)}` : 'PackOS reports have not been loaded yet.',
    },
    {
      id: 'install',
      name: `${selectedProfile.name} Install`,
      status: selectedReadiness?.install.installed ? 'healthy' : 'warning',
      detail: selectedReadiness?.install.installed ? `Installed at ${selectedReadiness.install.installPath}` : `${selectedProfile.name} is not installed yet.`,
    },
    {
      id: 'release',
      name: 'Catalog',
      status: selectedReadiness?.catalog.ok ? 'healthy' : 'warning',
      detail: selectedReadiness?.catalog.warnings.join(' ') || `${selectedReadiness?.catalog.releases ?? 0} approved releases loaded.`,
    },
    {
      id: 'launcher-profile',
      name: 'Minecraft Launcher Profile',
      status: selectedReadiness?.minecraftLauncher.ok ? 'healthy' : 'warning',
      detail: selectedReadiness?.minecraftLauncher.warnings.join(' ') || 'Handoff profile is ready.',
    },
    {
      id: 'logs',
      name: 'Logs',
      status: selectedReadiness?.logs.available ? 'healthy' : 'warning',
      detail: selectedReadiness?.logs.available ? `${selectedReadiness.logs.count} log files available.` : 'No launcher or install logs found yet.',
    },
  ] as const
  const resolvedExportVersion = exportVersion.trim() || selectedProfile?.version || fallbackExportVersion
  const resolvedExportFileName = ensureEchoPackFileName(exportFileName, resolvedExportVersion)
  const resolvedExportPath = exportOutputDir ? joinOutputPath(exportOutputDir, resolvedExportFileName) : resolvedExportFileName

  useEffect(() => {
    void refreshReadiness(selectedProfile.id)
    void refreshPackOs()
    logAnalyzer
      .readLatestLogs(selectedProfile.installPath)
      .then((entries) => {
        if (entries.length > 0) setLogEntries(entries)
      })
      .catch((error: unknown) => addToast('Log read failed', error instanceof Error ? error.message : 'Unable to read local logs.', 'warning'))
  }, [addToast, refreshPackOs, refreshReadiness, selectedProfile.id, selectedProfile.installPath])

  useEffect(() => {
    let disposed = false
    invokeNative('paths:get')
      .then((paths) => {
        if (!disposed) setExportOutputDir((current) => current || paths.exports)
      })
      .catch((error: unknown) => addToast('Export path unavailable', error instanceof Error ? error.message : 'Unable to read export folder.', 'warning'))
    return () => {
      disposed = true
    }
  }, [addToast])

  useEffect(() => {
    if (!repairActive) return
    const timer = window.setInterval(() => {
      if (document.visibilityState === 'visible') tickRepair()
    }, 400)
    return () => window.clearInterval(timer)
  }, [repairActive, tickRepair])

  useEffect(() => {
    if (!verifyActive) return
    const timer = window.setInterval(() => {
      if (document.visibilityState === 'visible') tickVerification()
    }, 360)
    return () => window.clearInterval(timer)
  }, [tickVerification, verifyActive])

  const beginRepair = async () => {
    startRepair()
    addToast('Repair install started', 'Verifying manifest files and repairing entries with configured artifact URLs.', 'info')
    try {
      const result = await repairService.runRepair({
        profileId: selectedProfile.id,
        installPath: selectedProfile.installPath,
        manifestPath: selectedProfile.manifestPath,
        backupConfigs: true,
        channel: selectedProfile.channel,
      })
      setRepairReport(result)
      setVerifyReport(result.after)
      finishRepair()
      finishVerification({
        scanned: result.after.scanned,
        total: result.after.scanned,
        errors: result.after.missing.length + result.after.corrupt.length,
        currentFile: result.skipped[0]?.path ?? result.repaired[0] ?? 'repair report complete',
      })
      addToast(
        result.ok ? (result.after.missing.length || result.after.corrupt.length ? 'Files repaired, launch still needs attention' : 'Repair install complete') : 'Repair completed with unresolved files',
        result.ok
          ? `Repaired ${result.repaired.length} files. Report: ${result.reportPath}`
          : `${result.after.missing.length + result.after.corrupt.length} files still need artifact URLs. Report: ${result.reportPath}`,
        result.ok ? 'success' : 'warning',
      )
    } catch (error) {
      finishRepair()
      addToast('Repair install failed', error instanceof Error ? error.message : 'Unable to run repair install.', 'danger')
    }
  }

  const beginVerification = async () => {
    startVerification()
    addToast('Hash verification started', 'Scanning installed files against the selected manifest.', 'info')
    try {
      const result = await invokeNative('manifest:verify', {
        profileId: selectedProfile.id,
        installPath: selectedProfile.installPath,
        manifestPath: selectedProfile.manifestPath,
      })
      setVerifyReport(result)
      finishVerification({
        scanned: result.scanned,
        total: result.scanned,
        errors: result.missing.length + result.corrupt.length,
        currentFile: result.results[0]?.path ?? 'manifest verification complete',
      })
      addToast(
        'Hash verification result',
        `${result.missing.length} missing and ${result.corrupt.length} corrupt files detected.`,
        result.missing.length || result.corrupt.length ? 'warning' : 'success',
      )
      void refreshReadiness(selectedProfile.id)
    } catch (error) {
      finishVerification({ scanned: 0, total: 0, errors: 0, currentFile: 'verification failed' })
      addToast('Hash verification failed', error instanceof Error ? error.message : 'Unable to verify manifest files.', 'danger')
    }
  }

  const exportDiagnosticReport = async () => {
    try {
      const result = await diagnosticReportService.exportReport(selectedProfile.id, selectedProfile.installPath)
      addToast(
        'Diagnostic report exported',
        `${result.reportPath} (${result.summary.missing} missing, ${result.summary.corrupt} corrupt, ${result.summary.logFiles} log files)`,
        'success',
      )
    } catch (error) {
      addToast('Diagnostic export failed', error instanceof Error ? error.message : 'Unable to export diagnostic report.', 'danger')
    }
  }

  const addExtraInclude = (kind: ExportExtraInclude['kind'], targetPath: string) => {
    setExtraIncludes((current) => {
      const key = targetPath.toLowerCase()
      if (current.some((item) => item.path.toLowerCase() === key)) return current
      return [...current, { kind, path: targetPath }]
    })
  }

  const selectExportOutputFolder = async () => {
    try {
      const result = await invokeNative('dialog:select-directory', {
        title: 'Select modpack export output folder',
        defaultPath: exportOutputDir || selectedProfile.installPath,
      })
      if (!result.canceled && result.path) setExportOutputDir(result.path)
    } catch (error) {
      addToast('Output folder selection failed', error instanceof Error ? error.message : 'Unable to select output folder.', 'danger')
    }
  }

  const selectExtraFolder = async () => {
    try {
      const result = await invokeNative('dialog:select-directory', {
        title: 'Add folder to this modpack export',
        defaultPath: selectedProfile.installPath,
      })
      if (!result.canceled && result.path) addExtraInclude('folder', result.path)
    } catch (error) {
      addToast('Folder selection failed', error instanceof Error ? error.message : 'Unable to add export folder.', 'danger')
    }
  }

  const selectExtraFile = async () => {
    try {
      const result = await invokeNative('dialog:select-file', {
        title: 'Add file to this modpack export',
        defaultPath: selectedProfile.installPath,
        filters: [{ name: 'All Files', extensions: ['*'] }],
      })
      if (!result.canceled && result.path) addExtraInclude('file', result.path)
    } catch (error) {
      addToast('File selection failed', error instanceof Error ? error.message : 'Unable to add export file.', 'danger')
    }
  }

  const resetExportDefaults = () => {
    const version = selectedProfile.version ?? fallbackExportVersion
    setExportVersion(version)
    setExportFileName(defaultExportFileName(version))
    setExportChangelog(defaultExportChangelog.join('\n'))
    setExportReleaseNotes(defaultReleaseNotes.join('\n'))
    setIncludeResourcepacks(true)
    setIncludeShaderpacks(true)
    setIncludeServerSafeFiles(true)
    setEmitReleaseSidecars(true)
    setExtraIncludes([])
    addToast('Export defaults restored', 'Default Ashfall export metadata and include options are back in place.', 'info')
  }

  const exportAshfallModpack = async () => {
    try {
      addToast('Ashfall export started', 'Creating a compressed .echo-pack.zip with embedded manifest and checksums.', 'info')
      const fileName = ensureEchoPackFileName(exportFileName, resolvedExportVersion)
      setExportFileName(fileName)
      const result = await invokeNative('pack:export', {
        profileId: selectedProfile.id,
        sourcePath: selectedProfile.installPath,
        outputDir: exportOutputDir || undefined,
        outputPath: exportOutputDir ? joinOutputPath(exportOutputDir, fileName) : undefined,
        version: resolvedExportVersion,
        extraIncludePaths: extraIncludes.map((item) => item.path),
        changelog: textLines(exportChangelog),
        releaseNotes: textLines(exportReleaseNotes),
        includeResourcepacks,
        includeShaderpacks,
        includeServerSafeFiles,
        emitReleaseSidecars,
      })
      setModpackExportReport(result)
      addToast(
        'Ashfall modpack exported',
        `${result.zipPath} (${result.counts.totalFiles} files, SHA-256 ${result.sha256.slice(0, 12)}...)`,
        'success',
      )
    } catch (error) {
      addToast('Ashfall export failed', error instanceof Error ? error.message : 'Unable to export Ashfall modpack.', 'danger')
    }
  }

  const copyReportValue = async (label: string, value: string) => {
    try {
      await navigator.clipboard.writeText(value)
      addToast(`${label} copied`, value, 'success')
    } catch {
      addToast('Copy unavailable', 'Clipboard access is not available in this window.', 'warning')
    }
  }

  const copyDiscordReport = async () => {
    const text = discordPostGenerator.createDiagnosticText(
      `Profile: ${selectedProfile.name}\nInstall: ${selectedProfile.installPath ?? 'not set'}\nLikely cause: ${analysis.likelyCause}`,
    )
    await navigator.clipboard.writeText(text)
      addToast('Support report copied', 'Discord-ready support summary copied to clipboard.', 'success')
  }

  const openSupportGuide = () => {
    if (supportGuideUrl) window.open(supportGuideUrl, '_blank', 'noopener,noreferrer')
  }

  const runAssetScan = async (moduleId: string) => {
    try {
      const report = await invokeNative('asset:validate', { moduleId, installPath: selectedProfile.installPath ?? '' })
      setAssetReport(report)
      addToast(`${moduleId} scan complete`, report.warnings[0] ?? 'No missing entries detected.', report.missing.length ? 'warning' : 'success')
    } catch (error) {
      addToast('Asset validation failed', error instanceof Error ? error.message : 'Unable to validate assets.', 'danger')
    }
  }

  const scanWorld = async () => {
    try {
      const folder = await invokeNative('dialog:select-directory', {
        title: 'Select Ashfall world folder',
        defaultPath: selectedProfile.installPath ? `${selectedProfile.installPath}\\saves` : undefined,
      })
      if (folder.canceled || !folder.path) return
      const report = await worldScannerService.scanWorld(folder.path, selectedProfile.id)
      setWorldReport(report)
      addToast(report.ok ? 'World scan clean' : 'World compatibility warning', report.warnings.join(' ') || report.recommendations[0], report.ok ? 'success' : 'warning')
    } catch (error) {
      addToast('World scan failed', error instanceof Error ? error.message : 'Unable to scan world.', 'danger')
    }
  }

  const refreshMinecraftLauncherStatus = async () => {
    try {
      const status = await launchService.minecraftLauncherStatus(selectedProfile.id, selectedProfile.installPath)
      setMinecraftLauncherStatus(status)
      addToast(
        status.profileCurrent ? 'Minecraft Launcher profile current' : 'Minecraft Launcher profile needs attention',
        status.warnings.join(' ') || `${status.profileName} is ready for handoff mode.`,
        status.profileCurrent ? 'success' : status.ok ? 'warning' : 'danger',
      )
    } catch (error) {
      addToast('Minecraft Launcher status failed', error instanceof Error ? error.message : 'Unable to inspect launcher profile state.', 'danger')
    }
  }

  const repairMinecraftLauncherDependency = async () => {
    try {
      const status = await launchService.ensureMinecraftLauncherDependency()
      const nextStatus = await launchService.minecraftLauncherStatus(selectedProfile.id, selectedProfile.installPath)
      setMinecraftLauncherStatus(nextStatus)
      addToast(
        status.ok ? 'Minecraft Launcher dependency ready' : 'Minecraft Launcher installer started',
        status.launcherExecutablePath ?? (status.launcherDependencyWarnings.join(' ') || 'Follow the official installer prompt, then retry Play.'),
        status.ok ? 'success' : 'warning',
      )
      void refreshReadiness(selectedProfile.id)
    } catch (error) {
      addToast('Launcher dependency repair failed', error instanceof Error ? error.message : 'Unable to repair Minecraft Launcher dependency.', 'danger')
    }
  }

  const openMinecraftLauncherFolder = async () => {
    const target = minecraftLauncherStatus?.launcherInstallPath ?? minecraftLauncherStatus?.minecraftRoot ?? minecraftLauncherStatus?.launcherInstallLogPath
    if (!target) {
      addToast('Launcher folder unavailable', 'Check Minecraft Launcher status first.', 'warning')
      return
    }
    try {
      await invokeNative('shell:open-path', { path: target })
    } catch (error) {
      addToast('Open launcher folder failed', error instanceof Error ? error.message : 'Unable to open launcher folder.', 'danger')
    }
  }

  const copyPackOsCommand = async (label: string, command: string | undefined) => {
    if (!command) {
      addToast('PackOS command unavailable', 'Run echoPackDoctor or generateEchoLauncherStatus from the ECHO repo.', 'warning')
      return
    }
    await copyReportValue(label, command)
  }

  const openMinecraftLauncher = async () => {
    try {
      const status = await launchService.openMinecraftLauncher(true)
      addToast(
        status.opened ? 'Minecraft Launcher opened' : 'Minecraft Launcher needs attention',
        status.launcherExecutablePath ?? status.launcherInstallPath ?? status.warnings?.[0] ?? 'Use the official launcher installer flow.',
        status.opened ? 'success' : 'warning',
      )
    } catch (error) {
      addToast('Minecraft Launcher open failed', error instanceof Error ? error.message : 'Unable to open Minecraft Launcher.', 'danger')
    }
  }

  const switchToPerformanceVariant = () => {
    setSelectedVariant('performance')
    applyPerformancePreset('low')
    addToast('Performance variant selected', 'Launcher UI state switched to the performance variant. No PackOS files were modified.', 'info')
  }

  const restoreLastKnownGood = async () => {
    addToast('Rollback restore started', 'Restoring the latest launcher-managed install/update rollback plan for this profile.', 'info')
    try {
      const result = await repairService.restoreLastKnownGood({
        profileId: selectedProfile.id,
        installPath: selectedProfile.installPath,
        manifestPath: selectedProfile.manifestPath,
      })
      setRollbackReport(result)
      if (result.after) {
        setVerifyReport(result.after)
        finishVerification({
          scanned: result.after.scanned,
          total: result.after.scanned,
          errors: result.after.missing.length + result.after.corrupt.length,
          currentFile: result.restored[0] ?? result.removed[0] ?? 'rollback restore complete',
        })
      }
      addToast(
        result.ok ? 'Last known good restored' : 'Rollback restore needs attention',
        result.ok
          ? `Restored ${result.restored.length} files and removed ${result.removed.length}. Report: ${result.reportPath}`
          : result.warnings.join(' ') || `Rollback report: ${result.reportPath}`,
        result.ok ? 'success' : 'warning',
      )
      void refreshReadiness(selectedProfile.id)
    } catch (error) {
      addToast('Rollback restore failed', error instanceof Error ? error.message : 'Unable to restore last known good install.', 'danger')
    }
  }

  const repairPlanCommand = packOsCommands.find((command) => command.includes('generateEchoRepairPlan')) ?? packOsCommands.find((command) => command.includes('echoPackDoctor'))
  const launcherStatusCommand = packOsCommands.find((command) => command.includes('generateEchoLauncherStatus')) ?? packOsCommands[0]

  return (
    <div className="space-y-6">
      <GlassCard tone={selectedReadiness?.ok ? 'success' : 'amber'}>
        <div className="flex flex-wrap items-center justify-between gap-4">
          <div>
            <p className="text-xs font-semibold uppercase text-amber-echo">System Status</p>
            <h2 className="mt-1 text-2xl font-semibold text-white">{selectedReadiness?.ok ? 'Ready' : 'Needs Attention'}</h2>
            <p className="mt-2 text-sm leading-6 text-slate-300">
              {selectedReadiness?.warnings[0] ?? `${selectedProfile.name} install, Catalog, launcher profile, and logs are connected.`}
            </p>
          </div>
          <div className="grid grid-cols-3 gap-3">
            <MetricCard icon={CheckCircle2} label="Installed" tone={selectedReadiness?.install.installed ? 'success' : 'amber'} value={selectedReadiness?.install.installed ? 'Yes' : 'No'} />
            <MetricCard icon={FileWarning} label="Warnings" tone={readinessWarnings ? 'amber' : 'success'} value={`${readinessWarnings}`} />
            <MetricCard icon={Bug} label="Logs" tone={selectedReadiness?.logs.available ? 'success' : 'amber'} value={`${selectedReadiness?.logs.count ?? 0}`} />
          </div>
        </div>
      </GlassCard>

      <Tabs.Root className="space-y-6" onValueChange={(value) => setActiveTab(value as ToolsTabId)} value={activeTab}>
        <Tabs.List className="glass-surface inline-flex rounded-xl p-1">
          {[
            { id: 'repair', label: 'Repair', icon: Wrench },
            { id: 'export', label: 'Export', icon: PackageOpen },
            { id: 'diagnostics', label: 'Diagnostics', icon: ClipboardList },
            { id: 'crash', label: 'Crash Analyzer', icon: Bug },
            { id: 'logs', label: 'Logs', icon: FileText },
            { id: 'ecosystem', label: 'Ecosystem', icon: Activity },
          ].map((tab) => {
            const Icon = tab.icon
            return (
              <Tabs.Trigger
                className="flex h-10 items-center gap-2 rounded-lg px-4 text-sm font-semibold text-slate-400 transition data-[state=active]:bg-cyan-echo/15 data-[state=active]:text-cyan-soft"
                key={tab.id}
                value={tab.id}
              >
                <Icon className="h-4 w-4" />
                {tab.label}
              </Tabs.Trigger>
            )
          })}
        </Tabs.List>

        <Tabs.Content className="space-y-6" value="repair">
          <div className="grid gap-6 xl:grid-cols-[1fr_420px]">
            <div className="space-y-6">
              <SectionHeader eyebrow="Repair Actions" title="Installation Recovery" />
              <div className="grid gap-4 md:grid-cols-2">
                {repairActions.map((action) => (
                  <GlassCard key={action.id} tone={action.recommended ? 'cyan' : 'default'}>
                    <div className="flex h-full flex-col justify-between gap-5">
                      <div>
                        <div className="mb-3 flex items-center justify-between gap-3">
                          <h3 className="font-semibold text-white">{action.title}</h3>
                          {action.recommended ? <StatusChip label="Recommended" status="update_available" /> : null}
                        </div>
                        <p className="text-sm leading-6 text-slate-300">{action.detail}</p>
                      </div>
                      <CyberButton
                        icon={action.id === 'reset-configs' ? RotateCcw : Hammer}
                        onClick={action.id === 'verify-files' ? beginVerification : beginRepair}
                        variant={action.recommended ? 'primary' : 'secondary'}
                      >
                        {action.id === 'repair-install' ? 'Repair Now' : action.title}
                      </CyberButton>
                    </div>
                  </GlassCard>
                ))}
                <GlassCard tone="amber">
                  <div className="flex h-full flex-col justify-between gap-5">
                    <div>
                      <div className="mb-3 flex items-center justify-between gap-3">
                        <h3 className="font-semibold text-white">Last Known Good</h3>
                        <StatusChip label="Rollback" status="warning" />
                      </div>
                      <p className="text-sm leading-6 text-slate-300">
                        Restores the latest launcher-managed install/update rollback plan for the selected profile and rechecks the restored manifest.
                      </p>
                    </div>
                    <CyberButton icon={Archive} onClick={() => void restoreLastKnownGood()} variant="warning">
                      Restore Last Known Good
                    </CyberButton>
                  </div>
                </GlassCard>
              </div>
            </div>

            <div className="space-y-6">
              <GlassCard tone="cyan">
                <SectionHeader eyebrow="Hash Verification" title="File Integrity" />
                <div className="space-y-4">
                  <div className="rounded-lg border border-cyan-soft/20 bg-white/[0.03] p-3">
                    <p className="text-xs text-slate-500">Current File</p>
                    <p className="font-mono text-sm text-white">{currentFile}</p>
                  </div>
                  <ProgressBar label="Verification progress" value={verifyProgress} />
                  <div className="grid grid-cols-2 gap-3 text-sm">
                    <div className="rounded-lg border border-cyan-soft/20 bg-white/[0.03] p-3">
                      <p className="text-slate-500">Scanned</p>
                      <p className="font-semibold text-white">{scannedFiles.toLocaleString()} / {totalFiles.toLocaleString()}</p>
                    </div>
                    <div className="rounded-lg border border-danger-echo/40 bg-danger-echo/10 p-3">
                      <p className="text-slate-500">Errors Found</p>
                      <p className="font-semibold text-red-100">{errorsFound}</p>
                    </div>
                    <div className="rounded-lg border border-cyan-soft/20 bg-white/[0.03] p-3">
                      <p className="text-slate-500">Last scan</p>
                      <p className="font-semibold text-white">{verifyReport ? `${verifyReport.scanned} files` : 'not run'}</p>
                    </div>
                    <div className="rounded-lg border border-cyan-soft/20 bg-white/[0.03] p-3">
                      <p className="text-slate-500">Valid files</p>
                      <p className="font-semibold text-white">{verifyReport ? verifyReport.valid.length.toLocaleString() : '0'}</p>
                    </div>
                  </div>
                  <CyberButton icon={FileJson} onClick={() => setActiveTab('logs')}>
                    View Detailed Log
                  </CyberButton>
                  {verifyReport ? (
                    <div className="rounded-lg border border-cyan-soft/20 bg-black/30 p-3 text-xs text-slate-300">
                      <p className="font-semibold text-white">Latest Verification</p>
                      <p className="mt-2">Install path: {verifyReport.installPath || selectedProfile.installPath || 'not set'}</p>
                      <p>Missing: {verifyReport.missing.join(', ') || 'none'}</p>
                      <p>Corrupt: {verifyReport.corrupt.join(', ') || 'none'}</p>
                    </div>
                  ) : null}
                </div>
              </GlassCard>

              {repairActive || repairProgress > 0 ? (
                <GlassCard tone={repairProgress === 100 ? 'success' : 'cyan'}>
                  <ProgressBar label="Repair progress" tone={repairProgress === 100 ? 'success' : 'cyan'} value={repairProgress} />
                  {repairReport ? (
                    <div className="mt-4 rounded-lg border border-cyan-soft/20 bg-black/30 p-3 text-xs text-slate-300">
                      <p className="font-semibold text-white">Repair Report</p>
                      <p className="mt-2">Report: {repairReport.reportPath}</p>
                      <p>Repaired: {repairReport.repaired.join(', ') || 'none'}</p>
                      <p>Skipped: {repairReport.skipped.map((item) => `${item.path} (${item.reason})`).join(', ') || 'none'}</p>
                    </div>
                  ) : null}
                </GlassCard>
              ) : null}

              {rollbackReport ? (
                <GlassCard tone={rollbackReport.ok ? 'success' : 'amber'}>
                  <SectionHeader eyebrow="Rollback Restore" title={rollbackReport.ok ? 'Last Known Good Restored' : 'Restore Needs Attention'} />
                  <div className="mt-4 rounded-lg border border-cyan-soft/20 bg-black/30 p-3 text-xs text-slate-300">
                    <p>Report: {rollbackReport.reportPath}</p>
                    <p>Plan: {rollbackReport.rollbackPlanPath}</p>
                    <p>Restored: {rollbackReport.restored.join(', ') || 'none'}</p>
                    <p>Removed: {rollbackReport.removed.join(', ') || 'none'}</p>
                    <p>Warnings: {rollbackReport.warnings.join(', ') || 'none'}</p>
                  </div>
                </GlassCard>
              ) : null}
            </div>
          </div>
        </Tabs.Content>

        <Tabs.Content className="space-y-6" value="export">
          <div className="grid gap-6 xl:grid-cols-[1fr_420px]">
            <GlassCard className="overflow-hidden p-0">
              <div className="relative min-h-64 overflow-hidden">
                <img alt="" className="absolute inset-0 h-full w-full object-cover" src={ashfallCardImage} />
                <div className="absolute inset-0 bg-gradient-to-r from-black via-slate-950/75 to-slate-950/25" />
                <div className="relative z-10 flex min-h-64 flex-col justify-end p-6">
                  <p className="text-xs font-semibold uppercase text-amber-echo">Modpack Export</p>
                  <h2 className="mt-2 text-3xl font-black text-white">Export Ashfall Modpack</h2>
                  <p className="mt-3 max-w-2xl text-sm leading-6 text-slate-200">
                    Create one compressed Ashfall .echo-pack.zip with pack files, embedded ECHO metadata, checksums, and optional strict-release sidecars.
                  </p>
                </div>
              </div>
              <div className="p-6">
                <div className="grid gap-3 md:grid-cols-3">
                  <MetricCard icon={PackageOpen} label="Format" value=".echo-pack.zip" />
                  <MetricCard icon={Archive} label="Pack" value="Ashfall" tone="success" />
                  <MetricCard icon={ShieldCheck} label="Hashes" value="SHA-256" tone="success" />
                </div>
                <div className="mt-5 grid gap-4 md:grid-cols-2">
                  <label className="space-y-2 text-xs font-semibold uppercase tracking-wide text-slate-500">
                    Version
                    <input
                      className="h-11 w-full rounded-lg border border-cyan-soft/20 bg-slate-950 px-3 text-sm normal-case tracking-normal text-white outline-none focus:border-cyan-echo"
                      onChange={(event) => {
                        const nextVersion = event.target.value
                        setExportVersion(nextVersion)
                        if (exportFileName === defaultExportFileName(exportVersion)) {
                          setExportFileName(defaultExportFileName(nextVersion))
                        }
                      }}
                      value={exportVersion}
                    />
                  </label>
                  <label className="space-y-2 text-xs font-semibold uppercase tracking-wide text-slate-500">
                    Output File Name
                    <input
                      className="h-11 w-full rounded-lg border border-cyan-soft/20 bg-slate-950 px-3 text-sm normal-case tracking-normal text-white outline-none focus:border-cyan-echo"
                      onChange={(event) => setExportFileName(event.target.value)}
                      value={exportFileName}
                    />
                  </label>
                  <label className="space-y-2 text-xs font-semibold uppercase tracking-wide text-slate-500 md:col-span-2">
                    Output Folder
                    <div className="flex gap-2">
                      <input
                        className="h-11 min-w-0 flex-1 rounded-lg border border-cyan-soft/20 bg-slate-950 px-3 font-mono text-xs normal-case tracking-normal text-white outline-none focus:border-cyan-echo"
                        onChange={(event) => setExportOutputDir(event.target.value)}
                        value={exportOutputDir}
                      />
                      <CyberButton icon={FolderOpen} onClick={() => void selectExportOutputFolder()} size="sm" variant="secondary">
                        Browse
                      </CyberButton>
                    </div>
                  </label>
                  <label className="space-y-2 text-xs font-semibold uppercase tracking-wide text-slate-500">
                    Manifest Changelog
                    <textarea
                      className="min-h-28 w-full rounded-lg border border-cyan-soft/20 bg-slate-950 px-3 py-2 text-sm normal-case tracking-normal text-white outline-none focus:border-cyan-echo"
                      onChange={(event) => setExportChangelog(event.target.value)}
                      value={exportChangelog}
                    />
                  </label>
                  <label className="space-y-2 text-xs font-semibold uppercase tracking-wide text-slate-500">
                    Release Notes
                    <textarea
                      className="min-h-28 w-full rounded-lg border border-cyan-soft/20 bg-slate-950 px-3 py-2 text-sm normal-case tracking-normal text-white outline-none focus:border-cyan-echo"
                      onChange={(event) => setExportReleaseNotes(event.target.value)}
                      value={exportReleaseNotes}
                    />
                  </label>
                </div>

                <div className="mt-5 grid gap-3 md:grid-cols-2">
                  <ToggleRow checked={includeResourcepacks} label="Include resourcepacks" onCheckedChange={setIncludeResourcepacks} />
                  <ToggleRow checked={includeShaderpacks} label="Include shaderpacks" onCheckedChange={setIncludeShaderpacks} />
                  <ToggleRow checked={includeServerSafeFiles} label="Include server-safe files" onCheckedChange={setIncludeServerSafeFiles} />
                  <ToggleRow checked={emitReleaseSidecars} label="Emit release sidecars" onCheckedChange={setEmitReleaseSidecars} />
                </div>

                <div className="mt-5 rounded-lg border border-cyan-soft/20 bg-white/[0.03] p-4">
                  <div className="flex flex-wrap items-start justify-between gap-3">
                    <div>
                      <p className="text-sm font-semibold text-white">Extra Files & Folders</p>
                      <p className="mt-1 text-xs leading-5 text-slate-400">Adds safe selections from inside the Ashfall instance on top of the default pack folders.</p>
                    </div>
                    <div className="flex flex-wrap gap-2">
                      <CyberButton icon={FolderPlus} onClick={() => void selectExtraFolder()} size="sm" variant="secondary">
                        Add Folder
                      </CyberButton>
                      <CyberButton icon={FilePlus} onClick={() => void selectExtraFile()} size="sm" variant="secondary">
                        Add File
                      </CyberButton>
                      <CyberButton icon={RotateCcw} onClick={resetExportDefaults} size="sm" variant="ghost">
                        Reset
                      </CyberButton>
                    </div>
                  </div>
                  {extraIncludes.length > 0 ? (
                    <div className="mt-4 space-y-2">
                      {extraIncludes.map((item) => (
                        <div className="flex items-center justify-between gap-3 rounded-lg border border-white/10 bg-black/25 px-3 py-2" key={`${item.kind}-${item.path}`}>
                          <div className="min-w-0">
                            <p className="text-xs font-semibold uppercase text-slate-500">{item.kind}</p>
                            <p className="break-all font-mono text-xs text-slate-200">{pathLabel(selectedProfile.installPath, item.path)}</p>
                          </div>
                          <button
                            aria-label={`Remove ${pathLabel(selectedProfile.installPath, item.path)}`}
                            className="flex h-8 w-8 shrink-0 items-center justify-center rounded-md border border-white/10 bg-white/5 text-slate-300 transition hover:bg-danger-echo/15 hover:text-red-100"
                            onClick={() => setExtraIncludes((current) => current.filter((entry) => entry !== item))}
                            type="button"
                          >
                            <Trash2 className="h-4 w-4" aria-hidden="true" />
                          </button>
                        </div>
                      ))}
                    </div>
                  ) : (
                    <p className="mt-4 rounded-lg border border-white/10 bg-black/20 p-3 text-sm text-slate-400">No extra picks yet. Defaults still include mods, config, defaultconfigs, datapacks, resourcepacks, and shaderpacks.</p>
                  )}
                  <div className="mt-4 rounded-lg border border-white/10 bg-black/25 p-3">
                    <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Resolved Output</p>
                    <p className="mt-1 break-all font-mono text-xs text-slate-200">{resolvedExportPath}</p>
                  </div>
                </div>

                <div className="mt-5 grid gap-4 md:grid-cols-2">
                  <div className="rounded-lg border border-white/10 bg-white/[0.03] p-4">
                    <p className="text-sm font-semibold text-white">Pack-safe content</p>
                    <p className="mt-2 text-sm leading-6 text-slate-300">mods, config, defaultconfigs, datapacks, resourcepacks, shaderpacks</p>
                  </div>
                  <div className="rounded-lg border border-amber-echo/35 bg-amber-echo/10 p-4">
                    <p className="text-sm font-semibold text-amber-100">Always excluded</p>
                    <p className="mt-2 text-sm leading-6 text-amber-100/90">saves, logs, screenshots, caches, auth, launcher profiles, options, crash reports, downloads, backups</p>
                  </div>
                </div>
                <CyberButton className="mt-5" icon={PackageOpen} onClick={() => void exportAshfallModpack()} variant="primary">
                  Export Ashfall Modpack
                </CyberButton>
              </div>
            </GlassCard>

            <GlassCard tone={modpackExportReport?.ok ? 'success' : 'default'}>
              <SectionHeader eyebrow="Export Report" title={modpackExportReport ? modpackExportReport.zipName : 'No Export Yet'} />
              {modpackExportReport ? (
                <div className="space-y-3 text-sm">
                  <ReportLine label="Archive" onCopy={copyReportValue} value={modpackExportReport.zipPath} />
                  <ReportLine label="SHA-256" onCopy={copyReportValue} value={modpackExportReport.sha256} />
                  <ReportLine label="Files" value={`${modpackExportReport.counts.totalFiles}`} />
                  <ReportLine label="Manifest" onCopy={copyReportValue} value={modpackExportReport.manifestPath || 'embedded only'} />
                  <ReportLine label="Release metadata" onCopy={copyReportValue} value={modpackExportReport.releaseMetadataPath || 'not emitted'} />
                  <ReportLine label="Needed jars" onCopy={copyReportValue} value={modpackExportReport.neededJarsPath ? `${modpackExportReport.neededJarsPath} (${modpackExportReport.neededJarsCount ?? 0})` : 'not emitted'} />
                  <ReportLine label="Excluded top-level paths" value={modpackExportReport.excludedTopLevel.join(', ') || 'none'} />
                  {modpackExportReport.warnings.length > 0 ? (
                    <div className="rounded-lg border border-amber-echo/40 bg-amber-echo/10 p-3 text-amber-100">
                      {modpackExportReport.warnings.join(' ')}
                    </div>
                  ) : null}
                </div>
              ) : (
                <p className="text-sm leading-6 text-slate-300">Exported archives will appear in the ECHO exports directory by default.</p>
              )}
            </GlassCard>
          </div>
        </Tabs.Content>

        <Tabs.Content className="space-y-6" value="diagnostics">
          <div className="grid gap-6 xl:grid-cols-[1fr_420px]">
            <GlassCard>
              <SectionHeader eyebrow="Ecosystem Health" title="Runtime Checks" />
              <div className="grid gap-3 md:grid-cols-2">
                {runtimeChecks.map((check, index) => {
                  const Icon = healthIcons[index]
                  return (
                    <div className="rounded-lg border border-cyan-soft/20 bg-white/[0.03] p-4" key={check.id}>
                      <div className="mb-3 flex items-center justify-between gap-3">
                        <div className="flex items-center gap-2 text-white">
                          <Icon className="h-4 w-4 text-cyan-soft" />
                          <span className="font-semibold">{check.name}</span>
                        </div>
                        <StatusChip compact status={check.status} />
                      </div>
                      <p className="text-sm leading-6 text-slate-300">{check.detail}</p>
                    </div>
                  )
                })}
              </div>
            </GlassCard>

            <GlassCard tone="cyan">
              <SectionHeader eyebrow="Diagnostic Summary" title="Ashfall" />
              <div className="grid grid-cols-2 gap-3">
                <MetricCard icon={ClipboardList} label="Checks" value={`${runtimeChecks.length}`} />
                <MetricCard icon={CheckCircle2} label="Ready" tone="success" value={`${runtimeChecks.filter((check) => check.status === 'healthy').length}`} />
                <MetricCard icon={FileWarning} label="Warnings" tone="amber" value={`${runtimeChecks.filter((check) => check.status !== 'healthy').length}`} />
                <MetricCard icon={Bug} label="Errors" tone="danger" value={`${verifyReport?.corrupt.length ?? 0}`} />
              </div>
              <div className="mt-4 space-y-2 rounded-lg border border-cyan-soft/20 bg-white/[0.03] p-4 text-sm">
                <SummaryRow label="Generated" value={selectedReadiness?.generatedAt ? new Date(selectedReadiness.generatedAt).toLocaleString() : 'readiness not loaded'} />
                <SummaryRow label="Catalog" value={selectedReadiness?.catalog.source ?? 'not loaded'} />
                <SummaryRow label="Install location" value={selectedProfile.installPath ?? 'not set'} />
                <SummaryRow label="Profile" value={selectedProfile.name} />
              </div>
              <div className="mt-4 grid gap-2">
                <CyberButton icon={Download} onClick={() => void exportDiagnosticReport()}>
                  Export Diagnostic Report
                </CyberButton>
                <CyberButton
                  icon={Send}
                  onClick={() => void copyDiscordReport()}
                  variant="secondary"
                >
                  Copy Support Report
                </CyberButton>
                {supportGuideUrl ? (
                  <CyberButton icon={Archive} onClick={openSupportGuide} variant="ghost">
                    View Support Guide
                  </CyberButton>
                ) : null}
                <CyberButton icon={RadioTower} onClick={() => void scanWorld()} variant="secondary">
                  Scan World Compatibility
                </CyberButton>
                <CyberButton icon={Volume2} onClick={() => void runAssetScan('echosoundcore')} variant="secondary">
                  Validate SoundCore Assets
                </CyberButton>
                <CyberButton icon={Terminal} onClick={() => void runAssetScan('echoweathercore')} variant="secondary">
                  Validate WeatherCore Profile
                </CyberButton>
              </div>
            </GlassCard>
          </div>
          <GlassCard tone={packOsHealthStatus(selectedPackOs) === 'critical' ? 'danger' : packOsHealthStatus(selectedPackOs) === 'warning' ? 'amber' : 'cyan'}>
            <div className="flex flex-wrap items-start justify-between gap-4">
              <div className="max-w-3xl">
                <SectionHeader eyebrow="PackOS Reports" title={selectedPackOs ? `${selectedPackOs.name} Launcher State` : 'PackOS State Unknown'} />
                <p className="text-sm leading-6 text-slate-300">
                  {selectedPackOs ? packOsPrimaryReason(packOs, selectedProfileId) : 'PackOS reports are missing or unreadable. The launcher will keep working, but report-driven launch gating is unknown.'}
                </p>
              </div>
              <StatusChip label={packOsUiStateLabel(selectedPackOs?.uiState)} status={packOsHealthStatus(selectedPackOs)} />
            </div>
            <div className="mt-4 grid gap-3 md:grid-cols-3">
              <SummaryRow label="Report root" value={packOs?.reportRoot ?? 'not detected'} />
              <SummaryRow label="Variant" value={selectedPackOs?.variant ?? 'unknown'} />
              <SummaryRow label="Channel" value={selectedPackOs?.channel ?? 'unknown'} />
              <SummaryRow label="Save compatibility" value={selectedPackOs?.saveCompatibilityVersion ?? 'unknown'} />
              <SummaryRow label="Readiness" value={selectedPackOs?.readinessStatus ?? 'unknown'} />
              <SummaryRow label="Lockfile" value={selectedPackOs?.lockfileStatus ?? 'unknown'} />
              <SummaryRow label="Install state" value={selectedPackOs?.installStateStatus ?? 'unknown'} />
              <SummaryRow label="Repair plan" value={selectedPackOs?.repairPlanStatus ?? 'unknown'} />
              <SummaryRow label="Recovery" value={selectedPackOs?.recoveryMode ?? 'unknown'} />
            </div>
            <div className="mt-4 grid gap-3 lg:grid-cols-[1fr_1fr]">
              <div className="rounded-lg border border-cyan-soft/20 bg-black/30 p-3">
                <p className="text-xs font-semibold uppercase text-slate-500">Report Inputs</p>
                <div className="mt-2 max-h-36 space-y-1 overflow-y-auto pr-1">
                  {(packOs?.reports ?? []).map((report) => (
                    <div className="flex items-center justify-between gap-3 text-xs" key={report.fileName}>
                      <span className="truncate font-mono text-slate-300">{report.fileName}</span>
                      <StatusChip compact label={report.status} status={report.status === 'loaded' ? 'healthy' : report.status === 'missing' ? 'missing' : 'warning'} />
                    </div>
                  ))}
                </div>
              </div>
              <div className="rounded-lg border border-cyan-soft/20 bg-black/30 p-3">
                <p className="text-xs font-semibold uppercase text-slate-500">Safe Commands</p>
                <div className="mt-2 max-h-36 space-y-2 overflow-y-auto pr-1">
                  {packOsCommands.length ? packOsCommands.map((command) => (
                    <button
                      className="block w-full truncate rounded-md border border-white/10 bg-white/[0.04] px-2 py-1 text-left font-mono text-xs text-cyan-soft hover:bg-cyan-echo/10"
                      key={command}
                      onClick={() => void copyPackOsCommand('PackOS command', command)}
                      type="button"
                    >
                      {command}
                    </button>
                  )) : <p className="text-sm text-slate-400">No safe command hints were reported.</p>}
                </div>
              </div>
            </div>
            <div className="mt-4 flex flex-wrap gap-2">
              <CyberButton icon={ShieldCheck} onClick={() => void beginVerification()} size="sm" variant="secondary">
                Verify Install
              </CyberButton>
              <CyberButton icon={FileJson} onClick={() => void copyPackOsCommand('Repair plan command', repairPlanCommand)} size="sm" variant="secondary">
                Generate Repair Plan
              </CyberButton>
              <CyberButton icon={Download} onClick={() => void exportDiagnosticReport()} size="sm" variant="secondary">
                Export Support Bundle
              </CyberButton>
              <CyberButton icon={ClipboardList} onClick={() => setActiveTab('diagnostics')} size="sm" variant="secondary">
                Open Diagnostics
              </CyberButton>
              <CyberButton icon={Terminal} onClick={() => setActiveTab('ecosystem')} size="sm" variant="secondary">
                Open Command Center
              </CyberButton>
              <CyberButton icon={RadioTower} onClick={() => void openMinecraftLauncher()} size="sm" variant="secondary">
                Open Minecraft Launcher
              </CyberButton>
              <CyberButton icon={RotateCcw} onClick={switchToPerformanceVariant} size="sm" variant="warning">
                Switch Performance
              </CyberButton>
              <CyberButton icon={Archive} onClick={() => void restoreLastKnownGood()} size="sm" variant="ghost">
                Restore Last Known Good
              </CyberButton>
              <CyberButton icon={Copy} onClick={() => void copyPackOsCommand('Launcher status command', launcherStatusCommand)} size="sm" variant="ghost">
                Copy Refresh Command
              </CyberButton>
            </div>
          </GlassCard>
          <GlassCard tone={minecraftLauncherStatus?.ok === false ? 'amber' : minecraftLauncherStatus?.profileCurrent ? 'success' : 'cyan'}>
            <div className="flex flex-wrap items-start justify-between gap-4">
              <div className="max-w-3xl">
                <SectionHeader
                  eyebrow="Minecraft Launcher Handoff"
                  title="Compatibility Profile Active"
                />
                <p className="text-sm leading-6 text-slate-300">
                  Diagnostics can verify the official Minecraft Launcher profile that ECHO writes for the selected pack. Handoff mode keeps ECHO in charge of install, repair, and validation while the Minecraft Launcher handles account auth and final play.
                </p>
              </div>
              <div className="flex flex-wrap gap-2">
                <StatusChip label="Handoff Mode" status="update_available" />
                {minecraftLauncherStatus ? (
                  <StatusChip
                    label={minecraftLauncherStatus.profileCurrent ? 'Profile Current' : minecraftLauncherStatus.ok ? 'Profile Missing/Outdated' : 'Blocked'}
                    status={minecraftLauncherStatus.profileCurrent ? 'healthy' : minecraftLauncherStatus.ok ? 'warning' : 'critical'}
                  />
                ) : null}
              </div>
            </div>
            {minecraftLauncherStatus ? (
              <div className="mt-4 grid gap-3 md:grid-cols-2">
                <SummaryRow label="Profile" value={minecraftLauncherStatus.profileName} />
                <SummaryRow
                  label="Version metadata"
                  value={
                    minecraftLauncherStatus.versionReady
                      ? `${minecraftLauncherStatus.versionId} (${minecraftLauncherStatus.versionSource ?? 'installed'})`
                      : `${minecraftLauncherStatus.versionId} pending`
                  }
                />
                <SummaryRow label="Game directory" value={minecraftLauncherStatus.gameDir} />
                <SummaryRow label="Minecraft root" value={minecraftLauncherStatus.minecraftRoot ?? 'not detected'} />
                <SummaryRow label="Metadata file" value={minecraftLauncherStatus.versionMetadataPath ?? 'not prepared'} />
                <SummaryRow label="Launcher dependency" value={minecraftLauncherStatus.launcherDependencySource ?? 'not checked'} />
                <SummaryRow label="Launcher executable" value={minecraftLauncherStatus.launcherExecutablePath ?? 'not detected'} />
                <SummaryRow label="Install log" value={minecraftLauncherStatus.launcherInstallLogPath ?? 'not written'} />
                <div className="md:col-span-2 rounded-lg border border-cyan-soft/20 bg-black/30 p-3 text-sm leading-6 text-slate-300">
                  <p className="font-semibold text-white">Profile report</p>
                  <p>{[...minecraftLauncherStatus.warnings, ...(minecraftLauncherStatus.launcherDependencyWarnings ?? [])].join(' ') || 'No handoff warnings detected.'}</p>
                </div>
              </div>
            ) : null}
            <div className="mt-4 flex flex-wrap gap-3">
              <CyberButton icon={RadioTower} onClick={() => void refreshMinecraftLauncherStatus()} variant="secondary">
                Check Minecraft Launcher Profile
              </CyberButton>
              <CyberButton icon={Wrench} onClick={() => void repairMinecraftLauncherDependency()} variant="secondary">
                Repair Launcher Dependency
              </CyberButton>
              <CyberButton icon={FolderOpen} onClick={() => void openMinecraftLauncherFolder()} variant="ghost">
                Open Launcher Folder
              </CyberButton>
            </div>
          </GlassCard>
          {worldReport || assetReport ? (
            <GlassCard tone={worldReport?.ok === false || (assetReport?.missing.length ?? 0) > 0 ? 'amber' : 'success'}>
              <SectionHeader eyebrow="Version 3 Validators" title="Latest Scan Result" />
              {worldReport ? (
                <div className="rounded-lg border border-cyan-soft/20 bg-black/30 p-3 text-sm leading-6 text-slate-300">
                  <p className="font-semibold text-white">World: {worldReport.worldPath}</p>
                  <p>Worldgen: {worldReport.currentWorldgenVersion} / Profile: {worldReport.profileWorldgenVersion}</p>
                  <p>Warnings: {worldReport.warnings.join(', ') || 'none'}</p>
                  <p>Recommendations: {worldReport.recommendations.join(', ') || 'none'}</p>
                </div>
              ) : null}
              {assetReport ? (
                <div className="mt-3 rounded-lg border border-cyan-soft/20 bg-black/30 p-3 text-sm leading-6 text-slate-300">
                  <p className="font-semibold text-white">{assetReport.moduleId} assets</p>
                  <p>Expected: {assetReport.expected}</p>
                  <p>Missing: {assetReport.missing.join(', ') || 'none'}</p>
                </div>
              ) : null}
            </GlassCard>
          ) : null}
        </Tabs.Content>

        <Tabs.Content className="space-y-6" value="crash">
          <div className="grid gap-6 xl:grid-cols-[0.8fr_1.2fr]">
            <div className="space-y-6">
              <CrashAnalyzerCard
                analysis={analysis}
                onOpenLog={() => setActiveTab('logs')}
                onRepair={beginRepair}
              />
              <GlassCard>
                <SectionHeader eyebrow="Recent Logs" title="Launch Trace" />
                <div className="space-y-2">
                  {logEntries.slice(0, 4).map((entry) => (
                    <div className="rounded-lg border border-cyan-soft/20 bg-black/30 p-3 font-mono text-xs" key={entry.id}>
                      <span className={entry.level === 'ERROR' ? 'text-danger-echo' : entry.level === 'WARN' ? 'text-amber-echo' : 'text-cyan-soft'}>
                        {entry.level}
                      </span>
                      <span className="mx-2 text-slate-500">{entry.source}</span>
                      <span className="text-slate-200">{entry.message}</span>
                    </div>
                  ))}
                </div>
              </GlassCard>
            </div>
            <GlassCard>
              <SectionHeader eyebrow="Crash Analyzer" title="Log Inspection" />
              <LogViewer
                entries={logEntries}
                onAction={(action) => {
                  if (action === 'Open folder') setActiveTab('logs')
                  else if (action === 'Copy summary' || action === 'Copy support report') void copyDiscordReport()
                }}
              />
            </GlassCard>
          </div>
        </Tabs.Content>

        <Tabs.Content className="space-y-6" value="logs">
          <LogsPage />
        </Tabs.Content>

        <Tabs.Content className="space-y-6" value="ecosystem">
          <EcosystemHealthPage />
        </Tabs.Content>
      </Tabs.Root>
    </div>
  )
}

function SummaryRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex justify-between gap-4">
      <span className="text-slate-500">{label}</span>
      <span className="text-right font-medium text-white">{value}</span>
    </div>
  )
}

function ReportLine({ label, onCopy, value }: { label: string; onCopy?: (label: string, value: string) => void; value: string }) {
  return (
    <div className="rounded-lg border border-cyan-soft/20 bg-black/30 p-3">
      <div className="flex items-center justify-between gap-3">
        <p className="text-xs text-slate-500">{label}</p>
        {onCopy ? (
          <button
            aria-label={`Copy ${label}`}
            className="rounded-md border border-white/10 bg-white/5 p-1 text-slate-300 transition hover:bg-white/10 hover:text-white"
            onClick={() => onCopy(label, value)}
            type="button"
          >
            <Copy className="h-3.5 w-3.5" aria-hidden="true" />
          </button>
        ) : null}
      </div>
      <p className="mt-1 break-all font-mono text-xs text-slate-200">{value}</p>
    </div>
  )
}
