import type { LaunchBlocker } from '../types/launch'

export interface LaunchPreflightSignals {
  javaValid: boolean
  missingFiles: number
  corruptFiles: number
  classpathCount: number
  neoforgeReady: boolean
}

export function buildLaunchBlockers(signals: LaunchPreflightSignals): LaunchBlocker[] {
  const blockers: LaunchBlocker[] = []
  if (!signals.javaValid) {
    blockers.push({ id: 'java', severity: 'critical', message: 'Java 25+ is required before launch.', action: 'Install or select Java 25+.' })
  }
  if (signals.missingFiles > 0 || signals.corruptFiles > 0) {
    blockers.push({
      id: 'files',
      severity: 'critical',
      message: `${signals.missingFiles} files missing and ${signals.corruptFiles} files corrupt.`,
      action: 'Run Install / Update or Repair Install.',
    })
  }
  if (signals.classpathCount === 0) {
    blockers.push({
      id: 'classpath',
      severity: 'critical',
      message: 'No Minecraft/NeoForge classpath was found.',
      action: 'Install the pack or add .echo/launch-plan.json generated by the release pipeline.',
    })
  }
  if (!signals.neoforgeReady) {
    blockers.push({ id: 'neoforge', severity: 'critical', message: 'NeoForge metadata is missing.', action: 'Install from a trusted ECHO manifest.' })
  }
  return blockers
}

export function redactLaunchCommand(command: string, accessToken: string) {
  return command.replaceAll(accessToken, '<minecraft-access-token>')
}

export function worldgenCompatibility(currentWorldgenVersion: string, profileWorldgenVersion: string, markerCount: number) {
  if (markerCount === 0) {
    return {
      ok: false,
      warning: 'No Ashfall worldgen marker was found in this world.',
    }
  }
  if (currentWorldgenVersion !== 'unknown' && currentWorldgenVersion !== profileWorldgenVersion) {
    return {
      ok: false,
      warning: `Worldgen marker ${currentWorldgenVersion} differs from selected profile ${profileWorldgenVersion}.`,
    }
  }
  return { ok: true, warning: '' }
}
